import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Printer, X } from 'lucide-react';
import { useRef } from 'react';

interface ReportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  report: {
    id: string;
    title: string;
    generatedAt: string;
    generatedBy: string;
  } | null;
}

const ReportDialog = ({ open, onOpenChange, report }: ReportDialogProps) => {
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    if (!report) return;
    
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>${report.title}</title>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; padding: 40px; margin: 0; color: #333; }
            .center { text-align: center; }
            .bold { font-weight: bold; }
            .line { border-top: 1px solid #ccc; margin: 20px 0; }
            .row { display: flex; justify-content: space-between; margin-bottom: 10px; }
            .branding { font-size: 24px; font-weight: bold; margin-bottom: 5px; color: #4F46E5; text-transform: uppercase; }
            .header-info { margin-bottom: 30px; }
            .footer { margin-top: 60px; font-style: italic; font-size: 12px; color: #666; text-align: center; }
            .content { line-height: 1.6; margin-top: 30px; min-height: 200px; border: 1px dashed #eee; padding: 20px; border-radius: 8px; background-color: #fafafa; }
            p { margin: 5px 0; }
          </style>
        </head>
        <body>
          <div class="center header-info">
             <div class="branding">VESMENDA SMARTSUITE</div>
             <p>Poblacion Pitogo Zamboanga Del Sur</p>
             <h2 style="margin-top:20px;">${report.title}</h2>
          </div>
          <div class="line"></div>
          <div class="row"><span><span class="bold">Report ID:</span> ${report.id}</span></div>
          <div class="row"><span><span class="bold">Generated By:</span> ${report.generatedBy}</span></div>
          <div class="row"><span><span class="bold">Generated Date:</span> ${report.generatedAt}</span></div>
          <div class="line"></div>
          
          <div class="content center">
             <p style="color: #888; margin-top: 80px;">[ ${report.title} Abstract ]</p>
             <p style="color: #888;">This is an officially generated system report summarizing all corresponding entries recorded up to <b>${report.generatedAt}</b>.</p>
          </div>

          <div class="footer">
            <p>This is a computer-generated document and may not require a signature.</p>
            <p style="margin-top:40px;">_________________________<br/><br/>Authorized Signature</p>
          </div>
        </body>
        <script>
          setTimeout(() => {
            window.print();
            window.onafterprint = function() { window.close(); };
          }, 500);
        </script>
      </html>
    `);
    printWindow.document.close();
  };

  if (!report) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl rounded-3xl overflow-hidden border-none shadow-2xl">
        <DialogHeader className="pt-6 px-6">
          <DialogTitle className="text-2xl font-bold flex items-center gap-2 text-primary">
            <Printer className="w-5 h-5" />
            System Report Viewer
          </DialogTitle>
        </DialogHeader>

        <div className="p-6">
          <div ref={reportRef} className="font-sans space-y-4 p-8 bg-white border border-gray-100 rounded-2xl shadow-inner relative">
            <div className="absolute top-4 right-4 py-1 px-3 bg-primary/10 text-primary rounded-full text-[10px] font-bold uppercase tracking-wider">
              OFFICIAL DOCUMENT
            </div>
            
            <div className="text-center space-y-1 mb-8">
              <p className="text-2xl font-black text-gray-900 tracking-tighter">VESMENDA<span className="text-primary">SMARTSUITE</span></p>
              <p className="text-xs text-gray-400">Poblacion Pitogo Zamboanga Del Sur</p>
            </div>

            <div className="text-center my-6">
                <h3 className="text-xl font-bold text-gray-800 uppercase tracking-widest border-b pb-2 inline-block px-4">
                  {report.title}
                </h3>
            </div>

            <div className="bg-gray-50 p-4 rounded-xl space-y-2 border border-gray-100">
              <div className="flex justify-between items-center text-sm">
                <span className="text-gray-400 font-medium">REPORT ID:</span>
                <span className="font-mono font-bold text-gray-700">{report.id}</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-gray-400 font-medium">GENERATED ON:</span>
                <span className="font-medium text-gray-700">{report.generatedAt}</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-gray-400 font-medium">ISSUED BY:</span>
                <span className="font-bold text-primary">{report.generatedBy}</span>
              </div>
            </div>

            <div className="mt-8 py-12 border-2 border-dashed border-gray-100 rounded-xl bg-gray-50/50 flex flex-col items-center justify-center text-center px-4">
                <p className="text-gray-400 font-medium text-sm italic">
                  This report abstract summarizes data associated with <b className="text-gray-600">{report.title}</b>.
                </p>
                <p className="text-xs text-gray-400 mt-2">
                  Click 'Print Document' to export the detailed physical copy.
                </p>
            </div>

          </div>

          <div className="flex gap-4 mt-8">
            <Button className="flex-1 h-12 bg-primary hover:bg-primary/90 text-white rounded-xl shadow-lg shadow-primary/20 transition-all active:scale-95 font-bold text-base" onClick={handlePrint}>
              <Printer className="w-5 h-5 mr-2" /> Print Document
            </Button>
            <Button variant="outline" className="h-12 border-gray-200 rounded-xl" onClick={() => onOpenChange(false)}>
              <X className="w-4 h-4 mr-2" /> Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ReportDialog;
